name: Java Maven Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "temurin"
          maven-version: "3.8.4"

      - name: Check Java and Maven versions
        run: |
          java -version
          mvn --version

      - name: Build and Test
        run: mvn clean install
